/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.util.ArrayList;
import java.util.Scanner;
import java.util.UUID;

public class App {
    public static void main(String[] args) {
        System.out.println("Running Train Booking System");
        Scanner scanner = new Scanner(System.in);
        int option = 0;

        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        }catch(Exception e){
            e.printStackTrace();
            return;
        }

        do{
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a seat");
            System.out.println("6. Cancel my booking");
            System.out.println("7. Exit the Application");

            option = scanner.nextInt();
            switch (option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = scanner.next();

                    User userToSignup = new User(nameToSignUp, passwordToSignUp,
                            UserServiceUtil.hashPassword(passwordToSignUp),
                                new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignup);
                    break;
                case 2:
                    System.out.println("Enter the username for login");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter the password for login");
                    String passwordToLogin = scanner.next();

                    User userToLogin = new User(nameToLogin,passwordToLogin);

                    try{
                        if(userBookingService.loginUser(userToLogin)){
                            System.out.println("Login successful");
                        }else{
                            System.out.println("Login unsuccessful");
                        }
                    }catch (Exception e){
                        e.printStackTrace();
                    }

            }

        }while(option != 7);

    }
}
